### ISSUE TITLE
Instructions isn't working

### ISSUE THREAD

**Issue by tborges** [jharris4/bootstrap-4-theme#1]
Hey @jharris4 
I got an error while I ran the code `npm run build` in my new project.
I got the error `npm ERR! missing script: build`.

![screenshot1](https://user-images.githubusercontent.com/11985578/53294376-70e41d80-379a-11e9-9e32-c4e74b7a733e.png)

Do you know what's wrong with it?
Thanks

**Comment by jharris4** [comment]
Hi @tborges, I hadn't tried building this package in quite a while, and when I did I got errors related to my installed node version being incompatible with `node-sass`.

After updating the package.json dependencies to the latest versions, the build does work fine.

```
yarn build
yarn run v1.13.0
$ npm run build-css && npm run build-min-css

> bootstrap-4-theme@1.0.2 build-css /Source/bootstrap-4-theme
> node-sass scss/bootstrap-theme.scss dist/bootstrap-theme.css

Rendering Complete, saving .css file...
Wrote CSS to /Source/bootstrap-4-theme/dist/bootstrap-theme.css

> bootstrap-4-theme@1.0.2 build-min-css /Source/bootstrap-4-theme
> node-sass scss/bootstrap-theme.scss dist/bootstrap-theme.min.css --output-style compressed

Rendering Complete, saving .css file...
Wrote CSS to /Source/bootstrap-4-theme/dist/bootstrap-theme.min.css
✨  Done in 1.49s.
```

Can you try the following and let me know if it works?

`git pull`
`yarn install`
`yarn build`

**Comment by tborges** [comment]
All right, I updated my package.json depencies from my Bootstrap-4-Theme. 
`
"devDependencies": {
    "bootstrap": "^4.3.1",
    "node-sass": "^4.11.0",
    "rimraf": "^2.6.3"
  },
`

...and still not working. :-(
![screen shot 2019-02-24 at 1 08 11 pm](https://user-images.githubusercontent.com/11985578/53305342-6c207780-3835-11e9-81b7-aa87d931a086.png)

**Comment by jharris4** [comment]
Not sure what to say, it runs fine over here.

Have you made a copy of the repo or something and changed the `package.json` file?

I recommend that you do a fresh clone of the repo and build, using the following steps:

`git clone https://github.com/jharris4/bootstrap-4-theme.git`
`cd bootstrap-4-theme`
`yarn install` (or `npm install`)
`yarn run build` (or `npm run build`)

I did those steps and it worked fine.

If that still doesn't work for you, then maybe there's an issue with the version of `node` or `npm` that you have installed.

I'm on Node `11.6.0` and Npm `6.5.0-next.0`

**Comment by tborges** [comment]
Oh, I see now.  It works for me now too if you do the `git clone ...`  first.  

Correct if I'm wrong/confused: What if, let's say I want to install `npm i bootstrap-4-theme` in my preexistent project (that's what I was doing). I still get the error that I mentioned earlier.   Maybe I'm drunk sorry, am I doing something wrong? 

My Node `10.15.1` and NPM `6.4.1`

**Comment by jharris4** [comment]
The build step is only for making changes to the scss file and building the css file, like if you were going to publish a new version of the package for use in other projects.

When the build runs, it creates the `.css` files under the `dist/` directory which is part of what is published to the npm repository.

How you actually use this package depends a lot on what tools you're using to build your own projects (like webpack or parcel).

With webpack, you can import the css or scss from the package using something like `import "bootstrap-4-theme/dist/bootstrap-theme.css"` or even `import "bootstrap-4-theme/scss/bootstrap-theme.scss"` if you have sass setup.

Another option you could use is just to copy the `bootstrap-theme.css` from the `dist` directory into your project and just use it as you would any other css file :-) (note that it's probably best to use the minified version `bootstrap-theme.min.css`)

If you go that route, you need to make sure you add the theme css file **AFTER** the main bootstrap css file in your html, something like:

```
<link rel="stylesheet" href="bootstrap.min.css">
<link rel="stylesheet" href="bootstrap-theme.min.css">
```

I hope that helps, let me know ;-)

**Comment by tborges** [comment]
Thanks a lot for explaining all that. You are right, there are different ways of use/install packages and I will get more educated on this topic.  I basically just started getting into building npm packages and your bootstrap-4-theme was my inspiration for my NPM project [Google-AMP-Template](https://www.npmjs.com/package/google-amp-template) on [GitHub as well](https://github.com/tborges/google-amp-template)  Thanks by the way.  I have no much time on my hands but I wanted to do something like that for while.  Maybe you could give some feedback/advice on my project, that would be awesome.

**Comment by jharris4** [comment]
ok i'll take a look. gonna close this issue now though...
